package iamdilipkumar.com.datastructures.programs;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 * <p>
 * Created on 16/07/17.
 *
 * @author dilipkumar4813
 * @version 1.0
 */

public class FibonnaciEvenSum {

    private static int first, second, sum;

    public static void main(String[] args) {
        first = 1;
        second = 2;
        sum = 0;

        calculateValue();
    }

    private static void calculateValue() {
        if (second <= 4000000) {
            if (second % 2 == 0) {
                sum += second;
            }

            int temp = first + second;
            first = second;
            second = temp;
            calculateValue();
        }else{
            System.out.println("Sum value: " + sum);
        }
    }
}
